# Generated by Django 2.0.3 on 2018-03-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(choices=[('Asia', 'Asia'), ('N. America', 'N. America'), ('S. America', 'S. America'), ('Europe', 'Europe'), ('Africa', 'Africa')], max_length=20)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='short',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Post'),
        ),
    ]
