# Generated by Django 2.0.3 on 2018-03-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180326_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='', width_field='width'),
        ),
    ]
