# Generated by Django 2.0.3 on 2018-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180326_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
