# Generated by Django 2.0.3 on 2018-03-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='ordering',
            new_name='order',
        ),
    ]
