# Generated by Django 2.0.3 on 2018-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20180326_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=None),
        ),
    ]
